/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/room.glb
*/

import { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";
import { useThree } from "react-three-fiber";
import * as THREE from "three";
import gsap from "gsap";

const Room = (props: any) => {
  const { nodes, materials }: any = useGLTF("/room.glb");
  const { camera } = useThree();

  const handleClick = (x: number, y: number, z: number) => {
    console.log(x, y, z);

    gsap.to(camera.position, {
      duration: 1,
      x,
      y,
      z,
      onUpdate: () => {
        camera.lookAt(1, 10, 0);
      },
      onComplete: () => {
        camera.lookAt(1, 10, 0);
      },
    });
    gsap.to(camera.rotation, {
      duration: 1,
      x: -10,
      y: 0,
      z: 0,
    });
  };
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Walls.geometry}
        material={materials.walls}
        position={[-0.63, 2.11, -0.86]}
      />
      <mesh
        geometry={nodes.Floor.geometry}
        material={materials.floor}
        position={[0, 0.15, 0]}
      />
      <mesh
        geometry={nodes.Walls001.geometry}
        material={materials.Material}
        position={[0.44, 3.14, -0.26]}
        scale={1.94}
      />
      <group position={[-0.79, 1.22, -1.27]} scale={0.84}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.cupboard} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Mirror} />
      </group>
      <mesh
        geometry={nodes.cupboard_handles.geometry}
        material={materials.Cupboard_handles}
        position={[-0.75, 1.2, -1.03]}
        scale={[0.02, 0.11, 0.01]}
      />
      <group
        position={[1.01, 1.38, -1.39]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.08}
      >
        <mesh geometry={nodes.Cube006.geometry} material={materials.shelf} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Mouse} />
      </group>
      <mesh
        geometry={nodes.shelf_handles.geometry}
        material={materials.Cupboard_handles}
        position={[1.01, 1.22, -1.23]}
        scale={[0.02, 0.11, 0.01]}
      />
      <group
        position={[0.39, 1.31, -1.28]}
        rotation={[0, 0.47, 0]}
        scale={[0.06, 0.01, 0.11]}
      >
        <mesh geometry={nodes.Cube016.geometry} material={materials.bed} />
        <mesh
          geometry={nodes.Cube016_1.geometry}
          material={materials.Computer_screen}
        />
      </group>
      <mesh
        geometry={nodes.Coffee_cup.geometry}
        material={materials.bed}
        position={[1.55, 1.3, -1.21]}
        scale={[0.04, 0.08, 0.04]}
      />
      <mesh
        geometry={nodes.computer_stand.geometry}
        material={materials.Mouse}
        position={[1.01, 1.31, -1.23]}
        scale={[-0.12, -0.01, -0.12]}
      />

      <group position={[1.1, 1.59, -1.21]} scale={1.32}>
        <mesh geometry={nodes.Cube010.geometry} material={materials.Mouse} />

        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials.Computer_screen}
          onPointerDown={() => handleClick(1, 0, 1)}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.computer_light}
        />
      </group>
      <motion.mesh
        whileHover={{ scale: 1.2 }}
        geometry={nodes.keyboard.geometry}
        material={materials.Mouse}
        position={[1.02, 1.3, -0.94]}
      />
      <group position={[1.48, 1.31, -0.97]} scale={[-0.04, -0.02, -0.08]}>
        <mesh geometry={nodes.Cube019.geometry} material={materials.Mouse} />
        <mesh
          geometry={nodes.Cube019_1.geometry}
          material={materials.mouse_scroller}
        />
      </group>
      <mesh
        geometry={nodes.Curve006.geometry}
        material={materials.Netflix}
        position={[1.03, 1.79, -1.21]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.35}
      />
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials.Netflix}
        position={[1.01, 1.56, -1.21]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.9}
      />
      <group position={[1.64, 1.82, -1.51]} rotation={[0, 1.52, 0]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials.modem} />
        <mesh
          geometry={nodes.Cube011_1.geometry}
          material={materials.modem_light}
        />
      </group>
      <group position={[-1.31, 3.39, -1.43]} scale={0.85}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.Mouse} />
        <mesh
          geometry={nodes.Cube003_1.geometry}
          material={materials.computer_light}
        />
        <mesh
          geometry={nodes.Cube003_2.geometry}
          material={materials.mouse_scroller}
        />
      </group>
      <group position={[-0.36, 3.39, -1.43]} scale={0.85}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.Mouse} />
        <mesh
          geometry={nodes.Cube004_1.geometry}
          material={materials.computer_light}
        />
        <mesh
          geometry={nodes.Cube004_2.geometry}
          material={materials.mouse_scroller}
        />
      </group>
      <mesh
        geometry={nodes.Wire.geometry}
        material={materials.Mouse}
        position={[-0.73, 2.8, -1.69]}
        scale={[-0.01, -0.02, -0.01]}
      />
      <mesh
        geometry={nodes.chandelier_stand.geometry}
        material={materials.floor}
        position={[0, 3.95, 0]}
        scale={[0.52, 0.21, 0.13]}
      />
      <mesh
        geometry={nodes.chandeliers.geometry}
        material={materials.window_frame}
        position={[0, 3.3, -0.05]}
        scale={[0.13, 0.17, 0.13]}
      />
      <mesh
        geometry={nodes.chandelier_rod.geometry}
        material={materials.Mouse}
        position={[0.01, 3.69, -0.05]}
        scale={[-0.01, -0.08, -0.01]}
      />
      <mesh
        geometry={nodes.chandelier_bulb.geometry}
        material={nodes.chandelier_bulb.material}
        position={[0.01, 2.99, -0.05]}
        scale={0.05}
      />
      <group
        position={[1, 2.82, -1.58]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.13, 1, 0.83]}
      >
        <mesh geometry={nodes.Plane.geometry} material={materials.curtain} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials.curtain} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.curtain} />
      </group>
      <mesh
        geometry={nodes.curtain_railing_1.geometry}
        material={materials.curtain_railings}
        position={[0.99, 3.77, -1.63]}
        scale={[1.12, 1, 1]}
      />
      <mesh
        geometry={nodes.curtain_loops_1.geometry}
        material={materials.curtain_railings}
        position={[1.55, 3.76, -1.58]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <group
        position={[-1.61, 2.18, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.77, 1, 1.4]}
      >
        <mesh geometry={nodes.Plane001.geometry} material={materials.curtain} />
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials.curtain}
        />
        <mesh
          geometry={nodes.Plane001_2.geometry}
          material={materials.curtain}
        />
      </group>
      <mesh
        geometry={nodes.curtain_railing_1001.geometry}
        material={materials.curtain_railings}
        position={[-1.66, 3.77, 0.73]}
        rotation={[0, 1.57, 0]}
        scale={[1.12, 1, 1]}
      />
      <mesh
        geometry={nodes.curtain_loops_1001.geometry}
        material={materials.curtain_railings}
        position={[-1.61, 3.76, -0.38]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.lamp.geometry}
        material={materials.lamp}
        position={[-1.53, 3.39, -0.75]}
        scale={[0.16, 0.25, 0.16]}
      />
      <mesh
        geometry={nodes.lamp_handle.geometry}
        material={materials.lamp_handle}
        position={[-1.66, 3.13, -0.75]}
        scale={[0.03, 0.15, 0.05]}
      />
      <mesh
        geometry={nodes.bed.geometry}
        material={materials.bed}
        position={[-0.69, 0.96, 1.4]}
      />
      <mesh
        geometry={nodes.pillows.geometry}
        material={materials.cushion}
        position={[-0.3, 1.14, 1.61]}
        rotation={[3.07, 0, 0]}
        scale={[0.27, 0.01, 0.24]}
      />
      <mesh
        geometry={nodes.bed_stands.geometry}
        material={materials.Mouse}
        position={[-0.69, 0.36, 0.74]}
        scale={[-0.03, -0.06, -0.03]}
      />
      <mesh
        geometry={nodes.bedsheet.geometry}
        material={materials.bedsheet}
        position={[-0.64, 0.9, 0.72]}
        rotation={[-0.7, 0, 0]}
        scale={[1.09, 1, 0.99]}
      />
      <mesh
        geometry={nodes.matress.geometry}
        material={materials.bedsheet}
        position={[-0.69, 0.84, 0.7]}
        scale={[0.66, 0.1, 1.01]}
      />
      <mesh
        geometry={nodes.pillows001.geometry}
        material={materials.cushion}
        position={[-0.48, 1.09, 0.67]}
        rotation={[3.07, 0, 0]}
        scale={[0.27, 0.01, 0.24]}
      />
      <mesh
        geometry={nodes.pillows002.geometry}
        material={materials.cushion}
        position={[-0.94, 1.11, 1.5]}
        rotation={[3.07, 0, 0]}
        scale={[0.27, 0.01, 0.24]}
      />
      <group position={[0.45, 1.71, -1.5]} scale={[1.11, 1.33, 1.11]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials.book} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials.modem} />
      </group>
      <group
        position={[0.45, 1.74, -1.5]}
        rotation={[0, -0.41, 0]}
        scale={[1.11, 1.33, 1.11]}
      >
        <mesh geometry={nodes.Cube014.geometry} material={materials.book} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials.modem} />
      </group>
      <group
        position={[0.45, 1.77, -1.5]}
        rotation={[0, 0.16, 0]}
        scale={[1.11, 1.33, 1.11]}
      >
        <mesh geometry={nodes.Cube015.geometry} material={materials.book} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials.modem} />
      </group>
      <group position={[0.99, 2.83, -1.71]} scale={[1, 0.89, 1]}>
        <mesh
          geometry={nodes.Cube005.geometry}
          material={materials.window_frame}
        />
        <mesh
          geometry={nodes.Cube005_1.geometry}
          material={materials.Window_emission}
        />
      </group>
      <group position={[-1.88, 2.16, 0.74]}>
        <mesh
          geometry={nodes.Cube023.geometry}
          material={materials.window_frame}
        />
        <mesh
          geometry={nodes.Cube023_1.geometry}
          material={materials.Window_emission}
        />
      </group>
      <group
        position={[1.37, 0.5, 1.24]}
        rotation={[-0.08, -0.33, -0.03]}
        scale={0.41}
      >
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials.puffy_chair}
        />
        <mesh
          geometry={nodes.Plane004_1.geometry}
          material={materials.puffy_chair}
        />
        <mesh
          geometry={nodes.Plane004_2.geometry}
          material={materials.puffy_chair}
        />
        <mesh
          geometry={nodes.Plane004_3.geometry}
          material={materials.puffy_chair}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/room.glb");
export default Room;
