/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public\pennyweb.glb --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import PulsingPresent from "../../components/PulsingCircle/PulsingPresent";

type GLTFResult = GLTF & {
  nodes: {
    Mesh004: THREE.Mesh;
    Mesh004_1: THREE.Mesh;
    Mesh004_2: THREE.Mesh;
    head_asset: THREE.Mesh;
  };
  materials: {
    body: THREE.MeshStandardMaterial;
    face1: THREE.MeshStandardMaterial;
    mouth1: THREE.MeshStandardMaterial;
  };
};

export default function PennyModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/pennyweb.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <pointLight
        position={[-0.562, 0.04, 0.011]}
        intensity={3}
        decay={0.1}
        color={"#8AC6FE"}
      />
      <directionalLight
        position={[5.0, 10.0, 7.5]}
        intensity={0.6}
        color={"#fe0000"}
      />
      <ambientLight intensity={20} color={"#222222"} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[0.09, -0.48, -1.64]}>
          <mesh geometry={nodes.Mesh004.geometry} material={materials.body} />
          <mesh
            geometry={nodes.Mesh004_1.geometry}
            material={materials.face1}
          />
          <mesh
            geometry={nodes.Mesh004_2.geometry}
            material={materials.mouth1}
          />
          <group position={[-4.5, 0, 1]}>
            {/* candle */}
            <Html>
              <PulsingPresent
                name={"กลิ่นร่ำควันเทียน"}
                description={
                  "หากขนมสัมปันนีถูกปิดซองกระดาษหรือถุงพลาสติกไว้ในที่ที่มีกลิ่นร่ำควันเทียนหอมกรุ่น จะทำให้กลิ่นร่ำควันเทียนหอมกรุ่นฝังลงไปในขนมสัมปันน และอาจทำให้ขนมสัมปันนีมีรสชาติและกลิ่นที่น่าสนใจมากขึ้น"
                }
              />
            </Html>
          </group>

          {/* body */}
          {/* ข้าง หน้า บน */}
          <group position={[2, 2, 5]}>
            <Html>
              <PulsingPresent
                name={"แป้งมันสำปะหลัง"}
                description={
                  "ขนมสัมปันนีทำจากแป้งมันสำปะหลัง ซึ่งจะมีสีขาวบอบบาง หอมหวาน มัน มีลักษณะที่นุ่มเนียน และไม่มีกลิ่นเหม็น"
                }
              />
            </Html>
          </group>
        </group>
        {/* flower headband */}
        <mesh
          geometry={nodes.head_asset.geometry}
          material={materials.body}
          position={[0.22, 0.05, -6.53]}
        >
          <group position={[2, 1, -1]}>
            <Html>
              <PulsingPresent
                name={"แม่พิมพ์ลวดลาย"}
                description={
                  "การสร้างรูปลักษณ์ของขนมสัมปันนีมักจะมีลักษณะเป็นแบบของแม่พิมพ์ดอกไม้ ที่มีลายสวยงามและชัดเจน โดยมักจะเน้นความละเอียดของรูปลักษณ์และความสวยงามเป็นหลัก"
                }
              />
            </Html>
          </group>
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/pennyweb.glb");
