/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public\yaku_real.glb --t
*/

import * as THREE from "three";
import React, { useRef, useState } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import YakuPopup from "../../components/DessertPopup/TalePopup";
import { motion } from "framer-motion-3d";
import PulsingModel from "../../components/PulsingCircle/PulsingModel";
import { useHover } from "../../hooks/useHover";
import PulsingPresent from "../../components/PulsingCircle/PulsingPresent";

type GLTFResult = GLTF & {
  nodes: {
    coconut_head: THREE.Mesh;
    coconut_milk_head: THREE.Mesh;
    body: THREE.Mesh;
    body_1: THREE.Mesh;
    body_2: THREE.Mesh;
    soybean: THREE.Mesh;
  };
  materials: {
    Yaku_body: THREE.MeshStandardMaterial;
    Yaku_eye: THREE.MeshStandardMaterial;
    YAku_mouth: THREE.MeshStandardMaterial;
  };
};

const YakuReal = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/yaku_real.glb") as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <pointLight
        position={[-0.562, 0.04, 0.011]}
        intensity={1}
        decay={0.1}
        color={"#FEFEFE"}
      />
      <directionalLight
        position={[5.0, 10.0, 7.5]}
        intensity={0.6}
        color={"#FE8442"}
      />
      <ambientLight intensity={20} color={"#222222"} />
      <mesh
        geometry={nodes.coconut_head.geometry}
        material={materials.Yaku_body}
        position={[-0.01, 0.07, -0.02]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <group position={[2, 1, -1.5]}>
          <Html>
            <PulsingPresent
              name={"มะพร้าว"}
              description={
                "เพิ่มมิติของรสชาติ และตกแต่งขนมให้สวยงามน่ารับประทาน"
              }
            />
          </Html>
        </group>
      </mesh>
      <mesh
        geometry={nodes.coconut_milk_head.geometry}
        material={materials.Yaku_body}
        position={[0, 0.03, -0.02]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <group position={[-4, 0.03, -0.02]}>
          <Html>
            <PulsingPresent
              name={"น้ำกะทิราดหน้า"}
              description={"ช่วยเพิ่มรสเค็ม เพื่อตัดกับรสหวานของขนม"}
            />
          </Html>
        </group>
      </mesh>
      <group
        position={[0, 0.01, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh geometry={nodes.body.geometry} material={materials.Yaku_body}>
          <group position={[-2, -3, 3]}>
            <Html>
              <PulsingPresent
                name={"ยาคู"}
                description={"เกิดมาจากแป้งและมีสีเขียวธรรมชาติจากใบเตย"}
              />
            </Html>
          </group>
        </mesh>
        <mesh geometry={nodes.body_1.geometry} material={materials.Yaku_eye} />
        <mesh
          geometry={nodes.body_2.geometry}
          material={materials.YAku_mouth}
        />
      </group>
      <group
        position={[0.01, 0.06, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh geometry={nodes.soybean.geometry} material={materials.Yaku_body}>
          <group position={[0, 0, -1]}>
            <Html>
              <PulsingPresent
                name={"ถั่วเหลือง"}
                description={
                  "เพิ่มรสสัมผัสที่หลากหลายให้แก่ขนมยาคู และยังช่วยเพิ่มสีสันให้ยาคูดูน่ากินมากขึ้นล่ะ"
                }
              />
            </Html>
          </group>
        </mesh>
      </group>
    </group>
  );
};

useGLTF.preload("/yaku_real.glb");
// React.memo(
export default React.memo(YakuReal);
