/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public\yakuweb.glb --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { PresentationControls, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh005: THREE.Mesh;
    Mesh005_1: THREE.Mesh;
    Mesh005_2: THREE.Mesh;
    coconut_head: THREE.Mesh;
    coconutmilk_head: THREE.Mesh;
    head_bean: THREE.Mesh;
    soy_bean: THREE.Mesh;
    floor_studio: THREE.Mesh;
  };
  materials: {
    Yaku_eye: THREE.MeshStandardMaterial;
    YAku_mouth: THREE.MeshStandardMaterial;
    Yaku_body: THREE.MeshStandardMaterial;
    floor: THREE.MeshStandardMaterial;
  };
};

export function YakuWeb(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/yakuweb.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <PresentationControls>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Mesh005.geometry}
            material={materials.Yaku_eye}
          />
          <mesh
            geometry={nodes.Mesh005_1.geometry}
            material={materials.YAku_mouth}
          />
          <mesh
            geometry={nodes.Mesh005_2.geometry}
            material={materials.Yaku_body}
          />
          <mesh
            geometry={nodes.coconut_head.geometry}
            material={materials.Yaku_body}
          />
          <mesh
            geometry={nodes.coconutmilk_head.geometry}
            material={materials.Yaku_body}
          />
          <mesh
            geometry={nodes.head_bean.geometry}
            material={materials.Yaku_body}
          />
          <mesh
            geometry={nodes.soy_bean.geometry}
            material={materials.Yaku_body}
          />
        </group>
      </PresentationControls>
      <mesh
        geometry={nodes.floor_studio.geometry}
        material={materials.floor}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/yakuweb.glb");
